sudo: false
language: python

python: '3.5'
# - '3.5'
# - '3.6'

# before_install: echo BEFORE ROOT INSTALL
# install: echo ROOT INSTALL

# before_cache: echo BEFORE CACHE

# after_success: echo AFTER SUCCESS ROOT
# after_failure: echo AFTER FAILURE ROOT

# before_script: echo BEFORE ROOT SCRIPT
# script: echo ROOT SCRIPT
# after_script: echo AFTER ROOT SCRIPT

# before_deploy: echo BEFORE DEPLOY ROOT
# deploy:
#   provider: script
#   script: echo ROOT DEPLOY!!!
#   on:
#     branch: master
#     tags: true
# after_deploy: echo AFTER DEPLOY ROOT


jobs:
  include:
  - stage: "Docker: Isolated"
    name: "cri docker:build-test docker:push-test"
    script: echo "cri docker:build-test docker:push-test"
  - stage: "Test: Lint"
    name: "cri lint:all"
    script: echo "cri lint:all"
  - stage: "Test: Isolated"
    name: "cri test:isolated (2.7)"
    script: echo "cri test:isolated"
    python: "2.7"
  - stage: "Test: Isolated"
    name: "cri test:isolated (3.4)"
    script: echo "cri test:isolated"
    python: "3.4"
  - stage: "Test: Isolated"
    name: "cri test:isolated (3.5)"
    script: echo "cri test:isolated"
    python: "3.5"
  - stage: "Docker: Integrated"
    name: "cri docker:build docker:push"
    script: echo "cri docker:build"
  - stage: "Deploy: Integrated"
    name:  "cri deploy:integrated"
    script: skip
    deploy:
      provider: script
      script: echo "cri deploy:integrated"
      on:
        branch: master
        tags: false
  - stage: "Test: Integrated"
    name: "cri test:integrated"
    script: echo "cri test:integrated"
  - stage: "Release: Create"
    name: "cri release:version"
    script: echo "cri release:version"
  - stage: "Deploy: Production"
    name: "cri deploy:production"
    script: skip
    deploy:
      provider: script
      script: echo "cri deploy:production"
      on:
        branch: master
        tags: true
        condition: $TRAVIS_TAG =~ (?n)^(?<Major>0|[1-9]\d*)\.(?<Minor>0|[1-9]\d*)\.(?<Patch>0|[1-9]\d*)(?<PreReleaseTagWithSeparator>-(?<PreReleaseTag>((0|[1-9]\d*|\d*[A-Z-a-z-][\dA-Za-z-]*))(\.(0|[1-9]\d*|\d*[A-Za-z-][\dA-Za-z-]*))*))?(?<BuildMetadataTagWithSeparator>\+(?<BuildMetadataTag>[\dA-Za-z-]+(\.[\dA-Za-z-]*)*))?$
stages:
  - name: "Docker: Isolated"
  - name: "Test: Lint"
  - name: "Test: Isolated"
  - name: "Docker: Integrated"
  - name: "Deploy: Integrated"
    if: branch = master
  - name: "Test: Integrated"
    if: branch = master
  - name: "Release: Create"
    if: branch = master
  - name: "Deploy: Production"
    if: branch = master AND tag =~ (?n)^(?<Major>0|[1-9]\d*)\.(?<Minor>0|[1-9]\d*)\.(?<Patch>0|[1-9]\d*)(?<PreReleaseTagWithSeparator>-(?<PreReleaseTag>((0|[1-9]\d*|\d*[A-Z-a-z-][\dA-Za-z-]*))(\.(0|[1-9]\d*|\d*[A-Za-z-][\dA-Za-z-]*))*))?(?<BuildMetadataTagWithSeparator>\+(?<BuildMetadataTag>[\dA-Za-z-]+(\.[\dA-Za-z-]*)*))?$



  # - name: "cri ci:test "
  #   script: echo TESTING && sleep 3
  # - stage: build
  #   name: "cri ci:build"
  #   script: echo BUILDING && sleep 3
  #   sudo: true
  # - stage: stage
  #   name: "cri ci:stage"
  #   script: echo STAGING && sleep 3
  # - stage: deploy
  #   name: "cri ci:deploy"
  #   script: echo DEPLOYING && sleep 3