sudo: true
language: python

python: '3.5'

before_install: "echo cri travis-ci:before-install"
install: "echo cri travis-ci:install"
before_script: "echo cri travis-ci:before-script"
script: "echo cri travis-ci:script"
before_cache: "echo cri travis-ci:before-cache"
after_success: "echo cri travis-ci:after-success"
after_failure: "echo cri travis-ci:after-failure"
before_deploy: "echo cri travis-ci:before-deploy"
deploy:
  provider: script
  script: "echo cri travis-ci:deploy"
  skip_cleanup: true
after_deploy: "echo cri travis-ci:after-deploy"
after_script: "echo cri travis-ci:after-script"

jobs:
  include:
  - stage: "Docker: Isolated"
    name: "cri docker:build-isolated docker:push-isolated"
    script: "echo cri docker:build-isolated docker:push-isolated"
  - stage: "Test: Isolated"
    name: "cri lint:all"
    script: "echo cri lint:all"
  - stage: "Test: Isolated"
    name: "cri test:isolated (2.7)"
    script: "echo cri test:isolated"
    python: "2.7"
  - stage: "Test: Isolated"
    name: "cri test:isolated (3.4)"
    script: "echo cri test:isolated"
    python: "3.4"
  - stage: "Test: Isolated"
    name: "cri test:isolated (3.5)"
    script: "echo cri test:isolated"
    python: "3.5"
  - stage: "Docker: Integrated"
    name: "cri docker:build-integrated docker:push-integrated"
    script: "echo cri docker:build-integrated docker:push-integrated"
  - stage: "Deploy: Integrated"
    name:  "cri deploy:integrated"
    script: skip
    deploy:
      provider: script
      script: "echo cri deploy:integrated"
      skip_cleanup: true
  - stage: "Test: Integrated"
    name: "cri test:integrated"
    script: "echo cri test:integrated"
  - stage: "Release: Create"
    if: branch = master AND tag = ""
    name: "cri release:version"
    script: "echo cri release:version"
  - stage: "Docker: Production"
    name: "cri docker:build-production docker:push-production"
    script: "echo cri docker:build-production docker:push-production"
    if: branch = master AND "tag =~ /(\d+\.)?(\d+\.)?(\*|\d+)$/"
  - stage: "Deploy: Production"
    name: "cri deploy:production"
    script: skip
    if: branch = master AND "tag =~ /(\d+\.)?(\d+\.)?(\*|\d+)$/"
    deploy:
      provider: script
      script: "echo cri deploy:production"
      skip_cleanup: true
      on:
        branch: master
        tags: true
        condition: $TRAVIS_TAG =~ /(\d+\.)?(\d+\.)?(\*|\d+)$/
stages:
  - name: "Docker: Isolated"
  - name: "Test: Isolated"
  - name: "Docker: Integrated"
  - name: "Deploy: Integrated"
  - name: "Test: Integrated"
  - name: "Release: Create"
    if: branch = master
  - name: "Docker: Production"
    if: "branch = master AND tag =~ /(\d+\.)?(\d+\.)?(\*|\d+)$/"
  - name: "Deploy: Production"
    if: "branch = master AND tag =~ /(\d+\.)?(\d+\.)?(\*|\d+)$/"
  